# Generated by Django 4.2.6 on 2023-10-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_profile_image_user_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileimage',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
